#These are account related.
config:
  account_name: <account_name>  #Used in URL for Historical API.
  user_name: <user_name>
  password_encoded: <pAsSwOrDeNcOdEd>  #At least some resemblance of security.
  #password: PlainTextPassword  #Use this is you want to use plain text, and comment out the encoded entry above.
  stream_type: track
  base_output_folder: ./output #Root folder for downloaded files.
  friendly_folder_names: true  #converts title into folder name by removing whitespace

